### ISSUE TITLE
Cannot Play Action Page

### ISSUE THREAD

**Issue by haritsahm** [ROBOTIS-GIT/ROBOTIS-OP3-Tools#12]
After i make a new action page and want to play that page, i got this error saying that the page has no action. The other issue is when i tried to play or try step 0 (g 0) such as the default WalkReady (Page 9) the joints are not even moving, but the command is completed. 

![error action](https://user-images.githubusercontent.com/26606913/40402734-9dbaf68c-5e77-11e8-96d6-e3a823d8df9c.png)
![error g0](https://user-images.githubusercontent.com/26606913/40402735-9deec69c-5e77-11e8-8374-167dec270855.png)

**Comment by kaym9n** [comment]
Hello @haritsahm 

If you edit or create a new aciton, you have to set the "page step" correctly.
For example in this image, "page step" should be set to "1". This is because STP0 is activated.

Follow the reference link and see the item 8.
Thanks.

reference : [emanual](http://emanual.robotis.com/docs/en/platform/op3/tutorials/#example-action-editing-with-op3_action_editor)
